### ISSUE TITLE
LoginUI

### ISSUE THREAD

**Issue by hoang-comartek** [comartek/fs-clone-tinwin-retailer#10]
https://github.com/comartek/fs-clone-tinwin-retailer/pull/8

**Comment by hoang-comartek** [comment]
check comment

**Comment by hoang-comartek** [comment]
resolve conflict @hiepbq-comartek

**Comment by hoang-comartek** [comment]
resolve conflict

![Image](https://user-images.githubusercontent.com/86939740/194259884-460987dd-c2f0-4420-9f29-0fda19d73975.png)

**Comment by phuongna-comartek** [comment]
@hiepbq-comartek  Cái này để lâu quá chưa thấy sửa?
