### ISSUE TITLE
Home Ui

### ISSUE THREAD

**Issue by hoang-comartek** [comartek/fs-clone-tinwin-retailer#11]
https://github.com/comartek/fs-clone-tinwin-retailer/pull/12

**Comment by hoang-comartek** [comment]
check comment

**Comment by nghiapt-comatek** [comment]
https://github.com/comartek/fs-clone-tinwin-retailer/pull/1

em chỉnh xong và đẩy lên lại rồi anh

**Comment by phuongna-comartek** [comment]
đã review, check lại comment nhé

**Comment by nghiapt-comatek** [comment]
đã chỉnh xong theo yêu cầu

**Comment by phuongna-comartek** [comment]
Done
