### ISSUE TITLE
build UI cart base, payment vs connect api home screen

### ISSUE THREAD

**Issue by nghiapt-comatek** [comartek/fs-clone-tinwin-retailer#17]

**Comment by phuongna-comartek** [comment]
@nghiapt-comatek  Check comment

**Comment by nghiapt-comatek** [comment]
https://github.com/comartek/fs-clone-tinwin-retailer/pull/18

**Comment by nghiapt-comatek** [comment]
đã check và đẩy lại code trong PR

**Comment by phuongna-comartek** [comment]
@nghiapt-comatek  check comment

**Comment by nghiapt-comatek** [comment]
@phuongna-comartek  đã chỉnh sửa và tách ra các file

**Comment by nghiapt-comatek** [comment]
@phuongna-comartek đã chỉnh lại URL lấy api
